default_language_version:
  python: python3.7

repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
      - id: reorder-python-imports
        exclude: migrations

  - repo: https://github.com/asottile/yesqa
    rev: v1.2.2
    hooks:
      - id: yesqa

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        exclude: migrations
        args:
          - --config=pyproject.toml

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        exclude: migrations
        additional_dependencies:
          - flake8_formatter_abspath==1.0.1
          - flake8-fixme==1.1.1
          - flake8-isort==3.0.1
          - flake8-unused-arguments==0.0.4
          - flake8-use-fstring==1.1


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
      - id: mypy
        exclude: migrations

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
